<?php

return [
    'online' => '在线',
    'offline' => '离线',
    'starting' => '启动中',
    'stopping' => '关闭中',
    'suspended' => '终止',
    'connection-error' => '连接错误',
    'transferring' => '转移中',
    'installing' => '安装中',
    'restoring-backup' => '备份恢复中',
    'unavailable' => '不可用',
    'status' => '状态',
    'CPU' => 'CPU',
    'memory' => '内存',
    'disk' => '储存空间',
    'unlimited' => '无限',
    'start' => '开启',
    'restart' => '重启',
    'stop' => '关闭',
    'kill' => '终止',
    'forcibly-stop-process' => '强制停止进程',
    'continue' => '继续',
    'forcibly-stopping-alert' => '强行停止服务器将导致数据损坏。',
    'cpu-usage' => 'CPU 使用率',
    'memory-usage' => '内存用量',
    'disk-usage' => '储存空间用量',
    'inbound-outbound' => '入站 / 出站',
    'low-resources' => '资源不足',
    'low-resources-desc' => '您的服务器资源不足，建议升级您的配置。',
    'upgrade-server' => '升级服务器',
    'cancel' => '取消',
    'copied-text' => '复制 {{text}} 到剪贴板。',
    'showing' => '展示',
    'to' => '到',
    'of' => '对',
    'results' => '结果。',
];