<?php

return [
    'file-manager' => '文件管理器',
    'search' => '搜索',
    'delete' => '删除',
    'move' => '移动',
    'archive' => '压缩',
    'unarchive' => '解压缩',
    'create-directory' => '创建目录',
    'upload' => '上传',
    'new-file' => '新文件',
    'rename' => '重命名',
    'permissions' => '权限',
    'copy' => '复制',
    'download' => '下载',
    'update' => '更新',
    'file-mode' => '文件模式',
    'you-cant-recover' => '一旦被删除，您将无法恢复',
    'once-deleted' => '的内容。',
    'delete-files' => '删除文件',
    'are-you-sure' => '您确定要删除',
    'this-is-permanent-action' => '这是一项永久性操作，文件无法被恢复。',
    'name' => '名称',
    'size' => '大小',
    'date' => '日期',
    'home' => '家',
    'container' => '容器',
    'is-empty' => '此目录似乎是空的。',
    'is-limited' => '该目录太大，无法在浏览器中显示，因此仅显示前 250 个文件。',
    'are-upload-click-to-view' => '文件正在上传中，点击查看',
    'cancel-uploads' => '取消上传',
    'cancel' => '取消',
    'close' => '关闭',
    'create' => '创建',
    'file-name' => '文件名',
    'file-name-description' => '输入该文件的保存名称。',
    'directory-will-be-as' => '此目录将被创建为',
    'rename-description' => '输入此文件或文件夹相对于当前目录的名称和新目录。',
    'new-location' => '新位置',
    'drag-and-drop' => '拖放文件以上传。',

    'edit' => [
        'youre-editing' => '你正在编辑一个',
        'will-be-exluded' => '文件。此处列出的任何文件或目录都将从备份中排除。支持使用星号作为通配符。',
        'you-can-negate' => '您可以在前面加上感叹号来否定先前的规则。',
        'save-content' => '保存内容',
        'create-file' => '创建文件',
    ],
];