<?php 

return [
    'schedules' => '计划',
    'manage-schedules' => '管理计划',
    'create-schedule' => '创建计划',
    'name' => '名称',
    'last-run-at' => '最后运行于',
    'next-run-at' => '下次运行于',
    'status' => '状态',
    'active' => '启用',
    'inactive' => '禁用',
    'processing' => '进行中',
    'manage-schedule' => '管理计划',
    'new-task' => '新任务',
    'run-now' => '现在运行',
    'editBtn' => '编辑',
    'n/a' => 'n/a',
    'never' => '从未运行',

    'no-schedules' => '此服务器没有计划任务。',
    'ignore-files-folders' => '忽略的文件 & 文件夹',
    'continues-on-failure' => '失败时继续',
    'later' => '之后',

    'minute' => '分钟',
    'hour' => '小时',
    'day' => '天',
    'week' => '周',
    'day-of-month' => '月中某日',
    'month' => '月',
    'day-of-week' => '周中某日',

    'deleteTask' => [
        'title' => '确认删除任务',
        'description' => '您确定要删除此任务吗？此操作无法撤销。',
        'delete' => '删除任务'
    ],
    'delete' => [
        'title' => '删除计划',
        'description' => '所有任务都将被删除，任何正在运行的进程都将被终止。',
        'delete' => '删除'
    ],
    'edit' => [
        'title-1' => '编辑计划',
        'title-2' => '创建新计划',

        'description' => '在定义任务开始运行的时间时，计划表系统支持使用 Cronjob 语法。使用上述字段指定这些任务开始运行的时间。',
        
        'name' => '计划名称',
        'name-description' => '此计划的可读标识符。',
        'cheatsheet' => '显示计划表',
        'cheatsheet-description' => '显示 cron 计划表以了解一些示例',
        'online-when-online' => '仅当服务器在线时',
        'online-when-online-description' => '只有在服务器处于在线状态时才执行此计划。',
        'enabled' => '启用计划',
        'enabled-description' => '如果启用，该计划将开始运行。',

        'save-changes' => '保存更改',
    ],
    'cheatsheet' => [
        'example' => '例子',
        'every-5-minutes' => '每 5 分钟',
        'every-hour' => '每小时',
        'hour-range' => '小时范围',
        'once-a-day' => '每天',
        'every-monday' => '每周一',
        'special-characters' => '特殊字符',
        'any-value' => '任何值',
        'value-list-separator' => '值列表分隔符',
        'range-values' => '范围值',
        'step-values' => '阶段值',
    ],
    'task' => [
        'message' => '当服务器的备份数量上限是 0 时，无法创建备份任务。',
        'edit-task' => '编辑任务',
        'save-changes' => '保存更改',
        'create-task' => '创建任务',
        'action' => '动作',
        'send-command' => '发送命令',
        'send-power-action' => '发送电源动作',
        'create-backup' => '创建备份',
        'offset' => '时间偏移（以秒为单位）',
        'offset-description' => '上一个任务执行完毕后，运行这个任务前需要等待的时间。如果这是计划中的第一个任务，则此值无效。',
        'payload' => '有效载荷',
        'ignored-files' => '忽略的文件',
        'ignored-files-description' => '可选。指定备份中要排除的文件和文件夹。默认情况下，将使用 .pteroignore 文件中的内容。如果已达到备份上限，将对最旧的备份进行轮换。',
        'start-server' => '启动服务器',
        'stop-server' => '关闭服务器',
        'restart-server' => '重启服务器',
        'kill-server' => '终止服务器',
        'continue-on-failure' => '失败后继续',
        'continue-on-failure-description' => '当该任务失败时，仍运行未来的任务。',
    ],
];